blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/${{ github.repository }}/blob/staging/CONTRIBUTING.md
    about: Read this first to understand how to contribute to this project if you haven't read it already.
