services:
  ws:
    build:
      context: .

    volumes:
      - .:/app

    ports:
      - "8080:8080"

    environment:
      WS_HOST: 0.0.0.0
      WS_PORT: 8080
      APP_ENV: development

    user: "${UID:-1000}:${GID:-1000}"

    command: composer start
